/*
 * Copyright (C) 2012 Simon Budig, <simon.budig@kernelconcepts.de>
 * Daniel Wagener <daniel.wagener@kernelconcepts.de> (M09 firmware support)
 * Lothar Waßmann <LW@KARO-electronics.de> (DT support)
 * Ulrich Becker <becker@inkatron.de> (electric noise canceling and a bit more
 *                                     object-oriented)
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/*
 * This is a driver for the EDT "Polytouch" family of touch controllers
 * based on the FocalTech FT5x06 line of chips.
 *
 * Development of this driver has been sponsored by Glyn:
 *    http://www.glyn.com/Products/Displays
 * And Sartorius Lab Instruments GmbH & Co. KG:
 *    https://www.sartorius.de
 */

#include <linux/module.h>
#include <linux/ratelimit.h>
#include <linux/interrupt.h>
#include <linux/input.h>
#include <linux/i2c.h>
#include <linux/uaccess.h>
#include <linux/delay.h>
#include <linux/debugfs.h>
#include <linux/slab.h>
#include <linux/gpio.h>
#include <linux/of_gpio.h>
#include <linux/input/mt.h>
#include <linux/input/touchscreen.h>
#include <linux/input/edt-ft5x06.h>

#ifndef STATIC_ASSERT
  #define __STATIC_ASSERT__( condition, line ) \
       extern char static_assertion_on_line_##line[2*((condition)!=0)-1];

  #define STATIC_ASSERT( condition ) __STATIC_ASSERT__( condition, __LINE__)
#endif

//#define CONFIG_DEBUG_EDT
#define CONFIG_EDT_IRQ_TOO_EARLY_CHECK

#define MAX_SUPPORT_POINTS		5

#define WORK_REGISTER_THRESHOLD		0x00
#define WORK_REGISTER_REPORT_RATE	0x08
#define WORK_REGISTER_GAIN		0x30
#define WORK_REGISTER_OFFSET		0x31
#define WORK_REGISTER_NUM_X		0x33
#define WORK_REGISTER_NUM_Y		0x34
#define NO_REGISTER			0xff

#define M09_REGISTER_THRESHOLD		0x80
#define M09_REGISTER_GAIN		0x92
#define M09_REGISTER_OFFSET		0x93
#define M09_REGISTER_NUM_X		0x94
#define M09_REGISTER_NUM_Y		0x95

#define NO_REGISTER			0xff

#define WORK_REGISTER_OPMODE		0x3c
#define FACTORY_REGISTER_OPMODE		0x01

#define EDT_NAME_LEN			23
#define EDT_SWITCH_MODE_RETRIES		10
#define EDT_SWITCH_MODE_DELAY		5 /* msec */
#define EDT_RAW_DATA_RETRIES		100
#define EDT_RAW_DATA_DELAY		1 /* msec */


#define CONFIG_EDT_TOUCH_DOWN_CHECK
#define CONFIG_EDT_BORDERS

#ifdef CONFIG_EDT_BORDERS
	#define EDT_DEFAULT_BORDER	22
#endif

/*
 * Minimum number of incoming interrupts after a first new
 * finger-contact, before the touch-event will forwarded to the
 * operating system.
 * This step could be necessary to cancel electrical noise interfering.
 * NOTE:
 * - When this value is set to zero no noise canceling will be done!
 * - The higher this value the more sluggish will be the touch-event!
 */
#define EDT_DEFAULT_MIN_RECEIVE_COUNT	1

/*
 * Touch-event-interrupt timeout in milliseconds.
 * This is a safety timeout for the case a touch-up (release) interrupt
 * is missing and makes sure that the OS becomes in any cases
 * a touch-up-event in this case generated by the timer-function.
 */
#define EDT_DEFAULT_TUOCH_TIMEOUT	100 /* msec */

#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
  #define IRQ_DEFAULT_MIN_INTERVAL_TIME	9 /* msec */
#endif


#ifdef CONFIG_DEBUG_EDT
   #define DEBUG_MESSAGE( constStr, n... ) \
      printk( KERN_DEBUG KBUILD_MODNAME "-dbg: " constStr, ## n )
#else
   #define DEBUG_MESSAGE( constStr, n... )
#endif

STATIC_ASSERT( sizeof(unsigned long) >= sizeof(void*) );

enum edt_ver {
	EDT_M06,
	EDT_M09,
	EDT_M12,
	GENERIC_FT,
};

struct edt_reg_addr {
	int reg_threshold;
	int reg_report_rate;
	int reg_gain;
	int reg_offset;
	int reg_num_x;
	int reg_num_y;
};

typedef u16 COORDINATES_T;
#define EDT_INVALID_POINT ((COORDINATES_T)~0)

#define EDT_DIMENSION_TO_COORDINATE( d ) ((d) * 64 - 1)

struct edt_point_t {
	COORDINATES_T x;
	COORDINATES_T y;
};

enum edt_event_t {
	TOUCH_EVENT_DOWN	= 0x00, /* can be received from touch-panel */
	TOUCH_EVENT_UP		= 0x01, /* can be received from touch-panel */
	TOUCH_EVENT_ON		= 0x02, /* can be received from touch-panel */
	TOUCH_EVENT_RESERVED	= 0x03, /* can be received from touch-panel */
	TOUCH_EVENT_NON		= 0xFF  /* will be set by this driver only */
};

struct edt_contact_t {
	unsigned long  time_stamp;
#ifdef CONFIG_DEBUG_EDT
	unsigned long  touch_down_time;
#endif
	int  touch_on_receive_count;
	bool was_new_input_read;
#ifdef CONFIG_EDT_TOUCH_DOWN_CHECK
	bool is_down;
#endif
	int  id;
	enum edt_event_t ev_type;
	struct edt_point_t point;
#ifdef CONFIG_DEBUG_FS
	struct edt_point_t last_point;
	struct dentry* p_debug_dir;
	enum edt_event_t last_event_type;
	enum edt_event_t current_event_type;
	u32 touch_up_count;
	u32 touch_on_count;
	u32 touch_down_count;
#ifdef CONFIG_EDT_BORDERS
	u32 border_hurt_up_count;
	u32 border_hurt_down_count;
	u32 border_hurt_left_count;
	u32 border_hurt_right_count;
#endif /* ifdef CONFIG_EDT_BORDERS */
#endif /* ifdef CONFIG_DEBUG_FS */
}; /* struct edt_contact_t */

struct edt_ft5x06_ts_data {
	struct i2c_client *p_i2c_client;
	struct input_dev *p_input_dev;
	struct edt_point_t dimension;
#ifdef CONFIG_EDT_BORDERS
	COORDINATES_T border_up;
	COORDINATES_T border_down;
	COORDINATES_T border_left;
	COORDINATES_T border_right;
#endif
	int reset_pin;
	int irq_pin;
	int wake_pin;
	int min_receive_count;
	int touch_timeout;
	int touch_maxdistance;
#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
	unsigned int irq_timestamp;
	unsigned int min_irq_interval_time; /* Minimum IRQ interval time in ms */
#endif
	struct edt_contact_t a_contacts[MAX_SUPPORT_POINTS];

#ifdef CONFIG_DEBUG_FS
	struct dentry *debug_dir;
	u8 *raw_buffer;
	size_t raw_bufsize;
	u32 irq_count;
	u32 wdt_count;
	u32 wdt_sync_count;
	u32 out_of_area_count;
	u32 check_summ_errors;
#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
	u32 irq_too_early_count;
#endif /* ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK */
#endif /* ifdef CONFIG_DEBUG_FS */

	spinlock_t spinlock;
	struct timer_list touch_up_timer;
	bool factory_mode;
	int threshold;
	int gain;
	int offset;
	int report_rate;

	char name[EDT_NAME_LEN];

	struct edt_reg_addr reg_addr;
	enum edt_ver version;
}; /* struct edt_ft5x06_ts_data */

/*
 * CAUTION!
 * The following macro of pointer-magic works only
 * if the children of the searched parent are a static
 * member-array in the type of parent!
 * In this case: a_contacts[MAX_SUPPORT_POINTS];
 */
#define EDT_GET_PARENT_OF( p_child ) 				\
	container_of( p_child, struct edt_ft5x06_ts_data,	\
		a_contacts[p_child->id] )


#ifdef CONFIG_DEBUG_EDT
#define __CASE_ITEM( i ) case i: return #i;
const char* dbg_show_event_type( enum edt_event_t ev )
{
	switch (ev) {
		__CASE_ITEM( TOUCH_EVENT_DOWN )
		__CASE_ITEM( TOUCH_EVENT_UP )
		__CASE_ITEM( TOUCH_EVENT_ON )
		__CASE_ITEM( TOUCH_EVENT_RESERVED )
		__CASE_ITEM( TOUCH_EVENT_NON )
	}
	return "unknown event";
}
#endif /* ifdef CONFIG_DEBUG_EDT */

inline static enum edt_event_t get_event( struct edt_contact_t* p_this )
{
	return p_this->ev_type;
}

static bool is_touched( struct edt_contact_t* p_this )
{
	switch (p_this->ev_type) {
		case TOUCH_EVENT_DOWN:
		case TOUCH_EVENT_ON:
			return true;
		default: break;
	}
	return false;
}

static void set_event( struct edt_contact_t* p_this, enum edt_event_t ev )
{
	struct edt_ft5x06_ts_data* p_parent = EDT_GET_PARENT_OF( p_this );

	switch (ev) {
		case TOUCH_EVENT_DOWN: {
			p_this->touch_on_receive_count = 0;
			break;
		}
		case TOUCH_EVENT_ON: {
			if (p_parent->min_receive_count == 0)
				break;
			/* In the case TOUCH_EVENT_DOWN was missing. */
			if (ev != p_this->ev_type && 
				p_this->ev_type != TOUCH_EVENT_DOWN) {
				p_this->touch_on_receive_count = 0;
				break;
			}
			if (p_this->touch_on_receive_count < 
					p_parent->min_receive_count)
				p_this->touch_on_receive_count++;
			break;
		}
		case TOUCH_EVENT_UP: {
			if (!is_touched( p_this ))
				dev_err_ratelimited(
					&p_parent->p_i2c_client->dev,
					"Event touch-up received without"
					" previously touch-down! ID=%d\n",
					p_this->id );
			p_this->point.x = EDT_INVALID_POINT;
			p_this->point.y = EDT_INVALID_POINT;
#ifdef CONFIG_EDT_TOUCH_DOWN_CHECK
			p_this->is_down = false;
#endif
			break;
		}
		default: break;
	}
	p_this->ev_type = ev;
}

static bool can_forward( struct edt_contact_t* p_this )
{
	struct edt_ft5x06_ts_data* p_parent = EDT_GET_PARENT_OF( p_this );
	if ( p_parent->min_receive_count == 0 )
		return true;

	if (p_this->touch_on_receive_count == 
		p_parent->min_receive_count) {
		//p_this->touch_on_receive_count = 0;
		return true;
	}
	return false;
}

static int edt_ft5x06_ts_readwrite(struct i2c_client *p_i2c_client,
				   u16 wr_len, u8 *wr_buf,
				   u16 rd_len, u8 *rd_buf)
{
	struct i2c_msg wrmsg[2];
	int i = 0;
	int ret;

	if (wr_len) {
		wrmsg[i].addr  = p_i2c_client->addr;
		wrmsg[i].flags = 0;
		wrmsg[i].len = wr_len;
		wrmsg[i].buf = wr_buf;
		i++;
	}
	if (rd_len) {
		wrmsg[i].addr  = p_i2c_client->addr;
		wrmsg[i].flags = I2C_M_RD;
		wrmsg[i].len = rd_len;
		wrmsg[i].buf = rd_buf;
		i++;
	}

	ret = i2c_transfer(p_i2c_client->adapter, wrmsg, i);
	if (ret < 0)
		return ret;
	if (ret != i)
		return -EIO;

	return 0;
}

static bool edt_ft5x06_ts_check_crc(struct edt_ft5x06_ts_data *p_tsdata,
				    u8 *buf, int buflen)
{
	int i;
	u8 crc = 0;

	for (i = 0; i < buflen - 1; i++)
		crc ^= buf[i];

	if (crc != buf[buflen-1]) {
		dev_err_ratelimited(&p_tsdata->p_i2c_client->dev,
				    "crc error: 0x%02x expected, got 0x%02x\n",
				    crc, buf[buflen-1]);
#ifdef CONFIG_DEBUG_FS
		p_tsdata->check_summ_errors++;
#endif
		return false;
	}

	return true;
}


static void report_contact( struct edt_contact_t* p_this )
{
	struct input_dev* p_input_dev = 
		EDT_GET_PARENT_OF( p_this )->p_input_dev;
	bool is_pressed = is_touched( p_this );
	input_mt_slot( p_input_dev, p_this->id );
	input_mt_report_slot_state( p_input_dev, MT_TOOL_FINGER, is_pressed );
	if (!is_pressed)
		return;
	input_report_abs( p_input_dev, ABS_MT_POSITION_X, p_this->point.x );
	input_report_abs( p_input_dev, ABS_MT_POSITION_Y, p_this->point.y );
}

static void sync_by_os( struct edt_ft5x06_ts_data* p_tsdata )
{
	input_mt_report_pointer_emulation( p_tsdata->p_input_dev, true );
	input_sync( p_tsdata->p_input_dev );
	DEBUG_MESSAGE( "sync!\n" );
}

static inline void edt_ft5x06_ts_report_state(
					struct edt_ft5x06_ts_data *p_tsdata )
{
	int id;
	bool sync_request = false;

	for (id = 0; id < MAX_SUPPORT_POINTS; id++) {
		struct edt_contact_t* p_contact = &p_tsdata->a_contacts[id];
		if ( !can_forward( p_contact ) )
			continue;
		sync_request = true;
		report_contact( p_contact );
	}

	if (sync_request)
		sync_by_os( p_tsdata );
}

static bool edt_is_eny_pressed( struct edt_ft5x06_ts_data* p_tsdata )
{
	int id;
	for (id = 0; id < MAX_SUPPORT_POINTS; id++) {
		if (is_touched( &p_tsdata->a_contacts[id] ))
			return true;
	}
	return false;
}

static inline bool is_event_unknown( enum edt_event_t ev )
{
	switch (ev) {
	case TOUCH_EVENT_DOWN:
	case TOUCH_EVENT_UP:
	case TOUCH_EVENT_ON:
		return false;
	default: break;
	}
	return true;
}

static irqreturn_t edt_ft5x06_ts_isr(int irq, void *dev_id)
{
	struct delta_t {
		int x;
		int y;
	};
	struct edt_ft5x06_ts_data *p_tsdata = dev_id;
	struct device *dev = &p_tsdata->p_i2c_client->dev;
	u8 cmd;
	u8 rdbuf[29];
	int i, id;
	int offset, tplen, datalen;
	volatile unsigned long current_jiffies;
	int error;
#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
	bool too_early;
#endif

#ifdef CONFIG_DEBUG_FS
	p_tsdata->irq_count++;
#endif

#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
	too_early = false;
	if (p_tsdata->min_irq_interval_time > 0) {
		current_jiffies = jiffies;
		if (time_after( p_tsdata->irq_timestamp + 
			msecs_to_jiffies(p_tsdata->min_irq_interval_time ),
			current_jiffies)) {
#ifdef CONFIG_DEBUG_FS
			p_tsdata->irq_too_early_count++;
#endif
			too_early = true;
		}
		p_tsdata->irq_timestamp = current_jiffies;
	}
#endif /* ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK */

	switch (p_tsdata->version) {
	case EDT_M06:
		cmd = 0xf9; /* tell the controller to send touch data */
		offset = 5; /* where the actual touch data starts */
		tplen = 4;  /* data comes in so called frames */
		datalen = 26; /* how much bytes to listen for */
		break;

	case EDT_M09:
	case EDT_M12:
	case GENERIC_FT:
		cmd = 0x02;
		offset = 1;
		tplen = 6;
		datalen = 29;
		break;

	default:
		goto out;
	}

	/*
	 * Disables the possible running touch-up-timer.
	 * (See below.)
	 */
	del_timer_sync(&p_tsdata->touch_up_timer);

	memset(rdbuf, 0, sizeof(rdbuf));
	error = edt_ft5x06_ts_readwrite(p_tsdata->p_i2c_client,
					sizeof(cmd), &cmd,
					datalen, rdbuf);
	if (error) {
		dev_err_ratelimited(dev, "Unable to fetch data, error: %d\n",
				    error);
		goto out;
	}

	/* M09/M12 does not send header or CRC */
	if (p_tsdata->version == EDT_M06) {
		if (rdbuf[0] != 0xaa || rdbuf[1] != 0xaa ||
			rdbuf[2] != datalen) {
			dev_err_ratelimited(dev,
					"Unexpected header: %02x%02x%02x!\n",
					rdbuf[0], rdbuf[1], rdbuf[2]);
			goto out;
		}

		if (!edt_ft5x06_ts_check_crc(p_tsdata, rdbuf, datalen))
			goto out;
	}

	current_jiffies = jiffies;

	/* Begin of touch-panel read-loop */
	for (i = 0; i < MAX_SUPPORT_POINTS; i++)
	{
		struct edt_point_t point;
		struct delta_t delta;
		struct edt_contact_t* p_contact;
		enum   edt_event_t type;
#ifdef CONFIG_EDT_BORDERS
		bool border_hurt;
#endif
		u8 *buf = &rdbuf[i * tplen + offset];

		type = buf[0] >> 6;

		/* ignore unknown events */
		if (is_event_unknown( type ))
			continue;
		/* M06 sometimes sends bogus coordinates in TOUCH_DOWN */
		if (p_tsdata->version == EDT_M06 && type == TOUCH_EVENT_DOWN)
			continue;
#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
		/* Touch-up-events may come earlier */
		if (too_early && (type != TOUCH_EVENT_UP) )
			continue;
#endif
		id = (buf[2] >> 4) & 0x0f;
		if ( id >= MAX_SUPPORT_POINTS ) {
			dev_err_ratelimited( dev, 
			"Touch-point-ID out of range: %d maximum: %d\n",
			id, MAX_SUPPORT_POINTS-1 );
			continue;
		}
		p_contact = &p_tsdata->a_contacts[id];
		BUG_ON( p_contact->id != id );
#ifdef CONFIG_EDT_TOUCH_DOWN_CHECK
		if (p_tsdata->version != EDT_M06) {
			if (type == TOUCH_EVENT_DOWN) {
				if (p_contact->is_down)
					continue;
				p_contact->is_down = true;
			}
			if (type == TOUCH_EVENT_ON && !p_contact->is_down)
				continue;
		}
#endif /* ifdef CONFIG_EDT_TOUCH_DOWN_CHECK */

#if (__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) || \
	(__BYTE_ORDER__ == __ORDER_PDP_ENDIAN__)
		point.x = ((buf[0] << 8) | buf[1]) & 0x0fff;
		point.y = ((buf[2] << 8) | buf[3]) & 0x0fff;
#elif (__BYTE_ORDER__ == __ORDER_BIG_ENDIAN__)
		point.x = ((buf[1] << 8) | buf[0]) & 0x0fff;
		point.y = ((buf[3] << 8) | buf[2]) & 0x0fff;
#else
	#error "Extremely fatal: Byte order (little or big endian) is unclear!"
#endif

#ifdef CONFIG_DEBUG_FS
		p_contact->last_event_type = 
				p_contact->current_event_type;
		p_contact->current_event_type = type;

		switch (type) {
		case TOUCH_EVENT_DOWN:
			p_contact->touch_down_count++;
			break;
		case TOUCH_EVENT_UP:
			p_contact->touch_up_count++;
			break;
		case TOUCH_EVENT_ON:
			p_contact->touch_on_count++;
			break;
		default: break;
		}

		switch (type) {
		case TOUCH_EVENT_DOWN:
		case TOUCH_EVENT_ON:
			p_contact->last_point = point;
			break;
		default: break;
		}
#endif /* ifdef CONFIG_DEBUG_FS */
#ifdef CONFIG_EDT_BORDERS
	if ((type == TOUCH_EVENT_ON) || (type == TOUCH_EVENT_DOWN)) {
		border_hurt = false;
		if (point.x < p_tsdata->border_left) {
#ifdef CONFIG_DEBUG_FS
			p_contact->border_hurt_left_count++;
#endif
			border_hurt = true;
		}
		if (point.x > (p_tsdata->dimension.x-p_tsdata->border_right)) {
#ifdef CONFIG_DEBUG_FS
			p_contact->border_hurt_right_count++;
#endif
			border_hurt = true;
		}
		if (point.y < p_tsdata->border_up) {
#ifdef CONFIG_DEBUG_FS
			p_contact->border_hurt_up_count++;
#endif
			border_hurt = true;
		}
		if (point.y > (p_tsdata->dimension.y-p_tsdata->border_down)) {
#ifdef CONFIG_DEBUG_FS
			p_contact->border_hurt_down_count++;
#endif
			border_hurt = true;
		}
		if ( border_hurt )
			continue;
	}
#endif /* ifdef CONFIG_EDT_BORDERS */


		DEBUG_MESSAGE( "ID=%d, count=%d, X=%d, Y=%d, Type=%s\n",
				id, p_contact->touch_on_receive_count,
				point.x, point.y, dbg_show_event_type(type) );

		if (p_tsdata->touch_maxdistance > 0 &&
			type == TOUCH_EVENT_ON) {
			if (p_contact->point.x != EDT_INVALID_POINT )
				delta.x = point.x - p_contact->point.x;
			else
				delta.x = 0;

			if (p_contact->point.y != EDT_INVALID_POINT )
				delta.y = point.y - p_contact->point.y;
			else
				delta.y = 0;

			/* treat out-of-boundary events as missing */
			if (delta.x * delta.x + delta.y * delta.y >
					p_tsdata->touch_maxdistance * 
					p_tsdata->touch_maxdistance) {
#ifdef CONFIG_DEBUG_FS
				p_tsdata->out_of_area_count++;
#endif
				continue;
			}
		}

#ifdef CONFIG_DEBUG_EDT
		if (type == TOUCH_EVENT_DOWN) {
			p_contact->touch_down_time = current_jiffies;
		} else {
			DEBUG_MESSAGE( "Duration: %u msec\n", 
					jiffies_to_msecs( current_jiffies -
					p_contact->touch_down_time ));
		}
#endif
#if 0
		/* too late reports for an ongoing event --> missing */
		if ( is_touched( p_contact ) &&
		    time_after (current_jiffies,
				p_contact->time_stamp +
				msecs_to_jiffies(p_tsdata->touch_timeout))) {
			DEBUG_MESSAGE( "Too late!\n" );
			continue;
		}
#endif
		set_event( p_contact, type );
		p_contact->was_new_input_read = true;
		p_contact->point = point;
		p_contact->time_stamp = current_jiffies;
	} /* End of touch-panel read-loop */

	for (i = 0; i < MAX_SUPPORT_POINTS; i++) {
		struct edt_contact_t* p_contact = &p_tsdata->a_contacts[i];
		if (p_contact->was_new_input_read) {
			p_contact->was_new_input_read = false;
			continue;
		}
		if (is_touched( p_contact )) {
			DEBUG_MESSAGE( "Missing touch-up of %d\n", i );
			set_event( p_contact, TOUCH_EVENT_UP );
		}
	}

	edt_ft5x06_ts_report_state( p_tsdata );

	if (edt_is_eny_pressed( p_tsdata ) ) {
		/*
		 * Starts the touch-up-timer for the case the expected
		 * interrupt containing a touch-up-message becomes missing
		 * e.g. due to a electrical interfering or a possible bug
		 * in the touch-panel firmware.
		 */
		//DEBUG_MESSAGE( "Start touch-up timer\n" );
		mod_timer (&p_tsdata->touch_up_timer,
		current_jiffies + msecs_to_jiffies(p_tsdata->touch_timeout));
	}

out:
	return IRQ_HANDLED;
}

/*
 * Interrupt-timeout:
 * It's a certain kind of watchdog-timer.
 *
 * Becomes invoked if at least one of the contacts are still
 * touched but no further interrupt of the touch-panel occurs.
 * In the case the receiving of the touch-up state was missing
 * for whatever reason.
 * In this case this will accomplished here, after the interrupt
 * touch-down interval-time has expired.
 * This makes it sure that a pressed button will released
 * in any cases.
 */
static void edt_ft5x06_touch_up_timer(unsigned long data)
{
	struct edt_ft5x06_ts_data *p_tsdata = (void *) data;
	int id;
	bool sync_request = false;

	spin_lock( &p_tsdata->spinlock );
#ifdef CONFIG_DEBUG_FS
	p_tsdata->wdt_count++;
#endif

	for (id = 0; id < MAX_SUPPORT_POINTS; id++) {
		struct edt_contact_t* p_contact = &p_tsdata->a_contacts[id];
		if (!is_touched( p_contact ))
			continue;
		if (!can_forward( p_contact ) )
			continue;
		sync_request = true;
		set_event( p_contact, TOUCH_EVENT_UP );
		report_contact( p_contact );
	}

	if (sync_request) {
		sync_by_os( p_tsdata );
#ifdef CONFIG_DEBUG_FS
		p_tsdata->wdt_sync_count++;
#endif
	}

	spin_unlock( &p_tsdata->spinlock );
}

static int edt_ft5x06_register_write(struct edt_ft5x06_ts_data *p_tsdata,
				     u8 addr, u8 value)
{
	u8 wrbuf[4];

	switch (p_tsdata->version) {
	case EDT_M06:
		wrbuf[0] = p_tsdata->factory_mode ? 0xf3 : 0xfc;
		wrbuf[1] = p_tsdata->factory_mode ? addr & 0x7f : addr & 0x3f;
		wrbuf[2] = value;
		wrbuf[3] = wrbuf[0] ^ wrbuf[1] ^ wrbuf[2];
		return edt_ft5x06_ts_readwrite(p_tsdata->p_i2c_client, 4,
					wrbuf, 0, NULL);
	case EDT_M09:
	case EDT_M12:
	case GENERIC_FT:
		wrbuf[0] = addr;
		wrbuf[1] = value;

		return edt_ft5x06_ts_readwrite(p_tsdata->p_i2c_client, 2,
					wrbuf, 0, NULL);

	default:
		return -EINVAL;
	}
}

static int edt_ft5x06_register_read(struct edt_ft5x06_ts_data *p_tsdata,
				    u8 addr)
{
	u8 wrbuf[2], rdbuf[2];
	int error;

	switch (p_tsdata->version) {
	case EDT_M06:
		wrbuf[0] = p_tsdata->factory_mode ? 0xf3 : 0xfc;
		wrbuf[1] = p_tsdata->factory_mode ? addr & 0x7f : addr & 0x3f;
		wrbuf[1] |= p_tsdata->factory_mode ? 0x80 : 0x40;

		error = edt_ft5x06_ts_readwrite(p_tsdata->p_i2c_client, 2,
						wrbuf, 2, rdbuf);
		if (error)
			return error;

		if ((wrbuf[0] ^ wrbuf[1] ^ rdbuf[0]) != rdbuf[1]) {
			dev_err(&p_tsdata->p_i2c_client->dev,
				"crc error: 0x%02x expected, got 0x%02x\n",
				wrbuf[0] ^ wrbuf[1] ^ rdbuf[0],
				rdbuf[1]);
			return -EIO;
		}
		break;

	case EDT_M09:
	case EDT_M12:
	case GENERIC_FT:
		wrbuf[0] = addr;
		error = edt_ft5x06_ts_readwrite(p_tsdata->p_i2c_client, 1,
						wrbuf, 1, rdbuf);
		if (error)
			return error;
		break;

	default:
		return -EINVAL;
	}

	return rdbuf[0];
}

struct edt_ft5x06_attribute {
	struct device_attribute dattr;
	size_t field_offset;
	u8 limit_low;
	u8 limit_high;
	u8 addr_m06;
	u8 addr_m09;
};

#define EDT_ATTR(_field, _mode, _addr_m06, _addr_m09,			\
		_limit_low, _limit_high)				\
	struct edt_ft5x06_attribute edt_ft5x06_attr_##_field = {	\
		.dattr = __ATTR(_field, _mode,				\
				edt_ft5x06_setting_show,		\
				edt_ft5x06_setting_store),		\
		.field_offset = offsetof(struct edt_ft5x06_ts_data, _field),\
		.addr_m06 = _addr_m06,					\
		.addr_m09 = _addr_m09,					\
		.limit_low = _limit_low,				\
		.limit_high = _limit_high,				\
	}

#define EDT_ATTR_ITEM(_field) &edt_ft5x06_attr_ ## _field.dattr.attr

static ssize_t edt_ft5x06_setting_show(struct device *dev,
				       struct device_attribute *dattr,
				       char *buf)
{
	struct i2c_client *p_i2c_client = to_i2c_client(dev);
	struct edt_ft5x06_ts_data *p_tsdata = i2c_get_clientdata(p_i2c_client);
	struct edt_ft5x06_attribute *attr =
			container_of(dattr, struct edt_ft5x06_attribute, dattr);
	u8 *field = (u8 *)p_tsdata + attr->field_offset;
	int val;
	size_t count = 0;
	int error = 0;
	u8 addr;

	spin_lock_irq( &p_tsdata->spinlock );

	if (p_tsdata->factory_mode) {
		error = -EIO;
		goto out;
	}

	switch (p_tsdata->version) {
	case EDT_M06:
		addr = attr->addr_m06;
		break;

	case EDT_M09:
	case EDT_M12:
	case GENERIC_FT:
		addr = attr->addr_m09;
		break;

	default:
		error = -ENODEV;
		goto out;
	}

	if (addr != NO_REGISTER) {
		val = edt_ft5x06_register_read(p_tsdata, addr);
		if (val < 0) {
			error = val;
			dev_err(&p_tsdata->p_i2c_client->dev,
				"Failed to fetch attribute %s, error %d\n",
				dattr->attr.name, error);
			goto out;
		}
	} else {
		val = *field;
	}

	if (val != *field) {
		dev_warn(&p_tsdata->p_i2c_client->dev,
			 "%s: read (%d) and stored value (%d) differ\n",
			 dattr->attr.name, val, *field);
		*field = val;
	}

	count = scnprintf(buf, PAGE_SIZE, "%d\n", val);
out:
	spin_unlock_irq( &p_tsdata->spinlock );
	return error ?: count;
}

static ssize_t edt_ft5x06_setting_store(struct device *dev,
					struct device_attribute *dattr,
					const char *buf, size_t count)
{
	struct i2c_client *client = to_i2c_client(dev);
	struct edt_ft5x06_ts_data *p_tsdata = i2c_get_clientdata(client);
	struct edt_ft5x06_attribute *attr =
			container_of(dattr, struct edt_ft5x06_attribute, dattr);
	u8 *field = (u8 *)p_tsdata + attr->field_offset;
	unsigned int val;
	int error;
	u8 addr;

	spin_lock_irq( &p_tsdata->spinlock );

	if (p_tsdata->factory_mode) {
		error = -EIO;
		goto out;
	}

	error = kstrtouint(buf, 0, &val);
	if (error)
		goto out;

	if (val < attr->limit_low || val > attr->limit_high) {
		error = -ERANGE;
		goto out;
	}

	switch (p_tsdata->version) {
	case EDT_M06:
		addr = attr->addr_m06;
		break;

	case EDT_M09:
	case EDT_M12:
	case GENERIC_FT:
		addr = attr->addr_m09;
		break;

	default:
		error = -ENODEV;
		goto out;
	}

	if (addr != NO_REGISTER) {
		error = edt_ft5x06_register_write(p_tsdata, addr, val);
		if (error) {
			dev_err(&p_tsdata->p_i2c_client->dev,
				"Failed to update attribute %s, error: %d\n",
				dattr->attr.name, error);
			goto out;
		}
	}
	*field = val;

out:
	spin_unlock_irq( &p_tsdata->spinlock );
	return error ?: count;
}


/* m06, m09: range 0-31, m12: range 0-5 */
static EDT_ATTR(gain, S_IWUSR | S_IRUGO, WORK_REGISTER_GAIN,
		M09_REGISTER_GAIN, 0, 31);
/* m06, m09: range 0-31, m12: range 0-16 */
static EDT_ATTR(offset, S_IWUSR | S_IRUGO, WORK_REGISTER_OFFSET,
		M09_REGISTER_OFFSET, 0, 31);
/* m06: range 20 to 80, m09: range 0 to 30, m12: range 1 to 255... */
static EDT_ATTR(threshold, S_IWUSR | S_IRUGO, WORK_REGISTER_THRESHOLD,
		M09_REGISTER_THRESHOLD, 0, 255);
/* m06: range 3 to 14, m12: (0x64: 100Hz) */
static EDT_ATTR(report_rate, S_IWUSR | S_IRUGO, WORK_REGISTER_REPORT_RATE,
		NO_REGISTER, 0, 255);

static EDT_ATTR(min_receive_count, S_IWUSR | S_IRUGO, NO_REGISTER, 
					NO_REGISTER, 0, 10);
static EDT_ATTR(touch_timeout, S_IWUSR | S_IRUGO, NO_REGISTER,
					NO_REGISTER, 20, 200);
static EDT_ATTR(touch_maxdistance, S_IWUSR | S_IRUGO, NO_REGISTER,
					NO_REGISTER, 0, 255);
#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
static EDT_ATTR(min_irq_interval_time, S_IWUSR | S_IRUGO, NO_REGISTER,
					NO_REGISTER, 0, 100);
#endif

#ifdef CONFIG_EDT_BORDERS
static EDT_ATTR( border_up, S_IWUSR | S_IRUGO, NO_REGISTER,
					NO_REGISTER, 0, 100);
static EDT_ATTR( border_down, S_IWUSR | S_IRUGO, NO_REGISTER,
					NO_REGISTER, 0, 100);
static EDT_ATTR( border_left, S_IWUSR | S_IRUGO, NO_REGISTER,
					NO_REGISTER, 0, 100);
static EDT_ATTR( border_right, S_IWUSR | S_IRUGO, NO_REGISTER,
					NO_REGISTER, 0, 100);
#endif

static struct attribute *edt_ft5x06_attrs[] = {
	EDT_ATTR_ITEM( gain ),
	EDT_ATTR_ITEM( offset ),
	EDT_ATTR_ITEM( threshold ),
	EDT_ATTR_ITEM( report_rate ),
	EDT_ATTR_ITEM( min_receive_count ),
	EDT_ATTR_ITEM( touch_timeout ),
	EDT_ATTR_ITEM( touch_maxdistance ),
#ifdef CONFIG_EDT_BORDERS
	EDT_ATTR_ITEM( border_up ),
	EDT_ATTR_ITEM( border_down ),
	EDT_ATTR_ITEM( border_left ),
	EDT_ATTR_ITEM( border_right ),
#endif
#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
	EDT_ATTR_ITEM( min_irq_interval_time ),
#endif
	NULL
};

static const struct attribute_group edt_ft5x06_attr_group = {
	.attrs = edt_ft5x06_attrs,
};

#ifdef CONFIG_DEBUG_FS
#define COORDINATE_TO_EDT_DIMENSION( c ) (((c) + 1) / 64)

static inline bool coordinates_invalid( struct edt_point_t* p )
{
	return ((p->x == EDT_INVALID_POINT) ||
		(p->y == EDT_INVALID_POINT));
}

static int edt_ft5x06_factory_mode(struct edt_ft5x06_ts_data *p_tsdata)
{
	struct i2c_client *p_i2c_client = p_tsdata->p_i2c_client;
	int retries = EDT_SWITCH_MODE_RETRIES;
	int ret;
	int error;

	disable_irq(p_i2c_client->irq);

	if (!p_tsdata->raw_buffer) {
		if (coordinates_invalid( &p_tsdata->dimension )) {
			error = -EINVAL;
			goto err_out;
		}
			
		p_tsdata->raw_bufsize = 
			COORDINATE_TO_EDT_DIMENSION(p_tsdata->dimension.x) *
			COORDINATE_TO_EDT_DIMENSION(p_tsdata->dimension.y) *
			sizeof(COORDINATES_T);
		p_tsdata->raw_buffer = kzalloc(p_tsdata->raw_bufsize,
					       GFP_KERNEL);
		if (!p_tsdata->raw_buffer) {
			error = -ENOMEM;
			goto err_out;
		}
	}

	/* mode register is 0x3c when in the work mode */
	if (p_tsdata->version != EDT_M06)
		goto m09_out;

	error = edt_ft5x06_register_write(p_tsdata, WORK_REGISTER_OPMODE, 0x03);
	if (error) {
		dev_err(&p_i2c_client->dev,
			"failed to switch to factory mode, error %d\n", error);
		goto err_out;
	}

	p_tsdata->factory_mode = true;
	do {
		mdelay(EDT_SWITCH_MODE_DELAY);
		/* mode register is 0x01 when in factory mode */
		ret = edt_ft5x06_register_read(p_tsdata, 
					       FACTORY_REGISTER_OPMODE);
		if (ret == 0x03)
			break;
	} while (--retries > 0);

	if (retries == 0) {
		dev_err(&p_i2c_client->dev, 
			"not in factory mode after %dms.\n",
			EDT_SWITCH_MODE_RETRIES * EDT_SWITCH_MODE_DELAY);
		error = -EIO;
		goto err_out;
	}

	return 0;

err_out:
	kfree(p_tsdata->raw_buffer);
	p_tsdata->raw_buffer = NULL;
	p_tsdata->factory_mode = false;
	enable_irq(p_i2c_client->irq);

	return error;

m09_out:
	dev_err(&p_i2c_client->dev,
		"No factory mode support for M09/M12/GENERIC_FT\n");
	return -EINVAL;

}

static int edt_ft5x06_work_mode(struct edt_ft5x06_ts_data *p_tsdata)
{
	struct i2c_client *p_i2c_client = p_tsdata->p_i2c_client;
	int retries = EDT_SWITCH_MODE_RETRIES;
	struct edt_reg_addr *reg_addr = &p_tsdata->reg_addr;
	int ret;
	int error;

	/* mode register is 0x01 when in the factory mode */
	error = edt_ft5x06_register_write(p_tsdata,
					  FACTORY_REGISTER_OPMODE, 0x1);
	if (error) {
		dev_err(&p_i2c_client->dev,
			"failed to switch to work mode, error: %d\n",
			error);
		return error;
	}

	p_tsdata->factory_mode = false;

	do {
		mdelay(EDT_SWITCH_MODE_DELAY);
		/* mode register is 0x01 when in factory mode */
		ret = edt_ft5x06_register_read(p_tsdata, WORK_REGISTER_OPMODE);
		if (ret == 0x01)
			break;
	} while (--retries > 0);

	if (retries == 0) {
		dev_err(&p_i2c_client->dev, "not in work mode after %dms.\n",
			EDT_SWITCH_MODE_RETRIES * EDT_SWITCH_MODE_DELAY);
		p_tsdata->factory_mode = true;
		return -EIO;
	}

	kfree(p_tsdata->raw_buffer);
	p_tsdata->raw_buffer = NULL;

	/* restore parameters */
	edt_ft5x06_register_write(p_tsdata, reg_addr->reg_threshold,
				  p_tsdata->threshold);
	edt_ft5x06_register_write(p_tsdata, reg_addr->reg_gain,
				  p_tsdata->gain);
	edt_ft5x06_register_write(p_tsdata, reg_addr->reg_offset,
				  p_tsdata->offset);
	if (reg_addr->reg_report_rate)
		edt_ft5x06_register_write(p_tsdata, reg_addr->reg_report_rate,
				  p_tsdata->report_rate);

	enable_irq(p_i2c_client->irq);

	return 0;
}

static int edt_ft5x06_debugfs_mode_get(void *data, u64 *mode)
{
	struct edt_ft5x06_ts_data *p_tsdata = data;

	*mode = p_tsdata->factory_mode;

	return 0;
};

static int edt_ft5x06_debugfs_mode_set(void *data, u64 mode)
{
	struct edt_ft5x06_ts_data *p_tsdata = data;
	int retval = 0;

	if (mode > 1)
		return -ERANGE;

	spin_lock_irq( &p_tsdata->spinlock );

	if (mode != p_tsdata->factory_mode) {
		retval = mode ? edt_ft5x06_factory_mode(p_tsdata) :
				edt_ft5x06_work_mode(p_tsdata);
	}

	spin_unlock_irq( &p_tsdata->spinlock );

	return retval;
};

DEFINE_SIMPLE_ATTRIBUTE(debugfs_mode_fops, edt_ft5x06_debugfs_mode_get,
			edt_ft5x06_debugfs_mode_set, "%llu\n");

static ssize_t edt_ft5x06_debugfs_raw_data_read(struct file *file,
				char __user *buf, size_t count, loff_t *off)
{
	struct edt_ft5x06_ts_data *p_tsdata = file->private_data;
	struct i2c_client *p_i2c_client = p_tsdata->p_i2c_client;
	int retries  = EDT_RAW_DATA_RETRIES;
	int val, i, j, error;
	size_t read = 0;
	int colbytes;
	char wrbuf[3];
	u8 *rdbuf;

	if (*off < 0 || *off >= p_tsdata->raw_bufsize)
		return 0;

	spin_lock_irq( &p_tsdata->spinlock );

	if (coordinates_invalid(&p_tsdata->dimension)) {
		error = -EINVAL;
		goto out;
	}
	
	if (!p_tsdata->factory_mode || !p_tsdata->raw_buffer) {
		error = -EIO;
		goto out;
	}

	error = edt_ft5x06_register_write(p_tsdata, 0x08, 0x01);
	if (error) {
		dev_dbg(&p_i2c_client->dev,
			"failed to write 0x08 register, error %d\n", error);
		goto out;
	}

	do {
		msleep(EDT_RAW_DATA_DELAY);
		val = edt_ft5x06_register_read(p_tsdata, 0x08);
		if (val < 1)
			break;
	} while (--retries > 0);

	if (val < 0) {
		error = val;
		dev_dbg(&p_i2c_client->dev,
			"failed to read 0x08 register, error %d\n", error);
		goto out;
	}

	if (retries == 0) {
		dev_dbg(&p_i2c_client->dev,
			"timed out waiting for register to settle\n");
		error = -ETIMEDOUT;
		goto out;
	}

	rdbuf = p_tsdata->raw_buffer;
	colbytes = COORDINATE_TO_EDT_DIMENSION(p_tsdata->dimension.y) *
		sizeof(COORDINATES_T);

	wrbuf[0] = 0xf5;
	wrbuf[1] = 0x0e;
	j = COORDINATE_TO_EDT_DIMENSION( p_tsdata->dimension.x );
	for (i = 0; i < j; i++) {
		wrbuf[2] = i;  /* column index */
		error = edt_ft5x06_ts_readwrite(p_tsdata->p_i2c_client,
						sizeof(wrbuf), wrbuf,
						colbytes, rdbuf);
		if (error)
			goto out;

		rdbuf += colbytes;
	}

	read = min_t(size_t, count, p_tsdata->raw_bufsize - *off);
	if (copy_to_user(buf, p_tsdata->raw_buffer + *off, read)) {
		error = -EFAULT;
		goto out;
	}

	*off += read;
out:
	spin_unlock_irq( &p_tsdata->spinlock );
	return error ?: read;
};

static const struct file_operations debugfs_raw_data_fops = {
	.open = simple_open,
	.read = edt_ft5x06_debugfs_raw_data_read,
};

static void
edt_ft5x06_ts_prepare_debugfs(struct edt_ft5x06_ts_data *p_tsdata,
			      const char *debugfs_name)
{
	int i;
	char contact_dir_name[32];

	p_tsdata->debug_dir = debugfs_create_dir(debugfs_name, NULL);
	if (!p_tsdata->debug_dir)
		return;

	for (i = 0; i < MAX_SUPPORT_POINTS; i++) {
		struct edt_contact_t* p_contact = &p_tsdata->a_contacts[i];

		snprintf( contact_dir_name, sizeof(contact_dir_name)-1,
			  "contact%d", i );
		p_contact->p_debug_dir = debugfs_create_dir( contact_dir_name,
						p_tsdata->debug_dir );
		if (!p_contact->p_debug_dir)
			continue;

		p_contact->last_event_type = TOUCH_EVENT_NON;
		debugfs_create_u8("last_event", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				(u8*)&p_contact->last_event_type);

		p_contact->current_event_type = TOUCH_EVENT_NON;
		debugfs_create_u8("current_event", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				(u8*)&p_contact->current_event_type);

		p_contact->touch_up_count = 0;
		debugfs_create_u32("touch_up_count", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->touch_up_count );

		p_contact->touch_on_count = 0;
		debugfs_create_u32("touch_on_count", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->touch_on_count );

		p_contact->touch_down_count = 0;
		debugfs_create_u32("touch_down_count", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->touch_down_count );

		p_contact->last_point.x = 0;
		debugfs_create_u16( "last_X", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->last_point.x );

		p_contact->last_point.y = 0;
		debugfs_create_u16( "last_Y", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->last_point.y );
#ifdef CONFIG_EDT_BORDERS
		p_contact->border_hurt_up_count = 0;
		debugfs_create_u32( "border_up", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->border_hurt_up_count );

		p_contact->border_hurt_down_count = 0;
		debugfs_create_u32( "border_down", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->border_hurt_down_count );

		p_contact->border_hurt_left_count = 0;
		debugfs_create_u32( "border_left", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->border_hurt_left_count );

		p_contact->border_hurt_right_count = 0;
		debugfs_create_u32( "border_right", S_IRUSR | S_IWUSR,
				p_contact->p_debug_dir,
				&p_contact->border_hurt_right_count );
#endif /* ifdef CONFIG_EDT_BORDERS */
	} /* for (i = 0; i < MAX_SUPPORT_POINTS; i++) */
	
	debugfs_create_u16("max_x", S_IRUSR, p_tsdata->debug_dir,
						 &p_tsdata->dimension.x);
	debugfs_create_u16("max_y", S_IRUSR, p_tsdata->debug_dir,
						 &p_tsdata->dimension.y);

	p_tsdata->irq_count = 0;
	debugfs_create_u32("irqs", S_IRUSR | S_IWUSR, p_tsdata->debug_dir,
				&p_tsdata->irq_count );

#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
	p_tsdata->irq_too_early_count = 0;
	debugfs_create_u32("irq_too_early", S_IRUSR | S_IWUSR,
				p_tsdata->debug_dir,
				&p_tsdata->irq_too_early_count );
#endif

	p_tsdata->out_of_area_count = 0;
	debugfs_create_u32("out_of_area", S_IRUSR | S_IWUSR, 
			   p_tsdata->debug_dir, &p_tsdata->out_of_area_count );
	
	p_tsdata->wdt_count = 0;
	debugfs_create_u32("wdt", S_IRUSR | S_IWUSR, p_tsdata->debug_dir,
				&p_tsdata->wdt_count );
			
	p_tsdata->wdt_sync_count = 0;
	debugfs_create_u32("wdt_sync", S_IRUSR | S_IWUSR, p_tsdata->debug_dir,
				&p_tsdata->wdt_sync_count );

	p_tsdata->check_summ_errors = 0;
	debugfs_create_u32("check_summ_errors", S_IRUSR | S_IWUSR,
				p_tsdata->debug_dir, 
				&p_tsdata->check_summ_errors );

	debugfs_create_file("mode", S_IRUSR | S_IWUSR,
				p_tsdata->debug_dir, p_tsdata,
				&debugfs_mode_fops);

	debugfs_create_file("raw_data", S_IRUSR,
				p_tsdata->debug_dir, p_tsdata,
				&debugfs_raw_data_fops);
}

static void
edt_ft5x06_ts_teardown_debugfs(struct edt_ft5x06_ts_data *p_tsdata)
{
	debugfs_remove_recursive(p_tsdata->debug_dir);
	kfree(p_tsdata->raw_buffer);
}


#else /* CONFIG_DEBUGFS */

static inline void
edt_ft5x06_ts_prepare_debugfs(struct edt_ft5x06_ts_data *p_tsdata,
				const char *debugfs_name)
{
}

static inline void
edt_ft5x06_ts_teardown_debugfs(struct edt_ft5x06_ts_data *p_tsdata)
{
}

#endif /* /CONFIG_DEBUGFS */

static int edt_ft5x06_ts_reset(struct i2c_client *client,
			struct edt_ft5x06_ts_data *p_tsdata)
{
	int error;

	if (gpio_is_valid(p_tsdata->wake_pin)) {
		error = devm_gpio_request_one(&client->dev,
					p_tsdata->wake_pin, GPIOF_OUT_INIT_LOW,
					"edt-ft5x06 wake");
		if (error) {
			dev_err(&client->dev,
				"Failed to request GPIO %d as wake pin,"
				" error %d\n",
				p_tsdata->wake_pin, error);
			return error;
		}

		msleep(5);
		gpio_set_value(p_tsdata->wake_pin, 1);
	}
	if (gpio_is_valid(p_tsdata->reset_pin)) {
		/* this pulls reset down, enabling the low active reset */
		error = devm_gpio_request_one(&client->dev,
					p_tsdata->reset_pin,
					GPIOF_OUT_INIT_LOW,
					"edt-ft5x06 reset");
		if (error) {
			dev_err(&client->dev,
				"Failed to request GPIO %d as reset pin,"
				" error %d\n",
				p_tsdata->reset_pin, error);
			return error;
		}

		msleep(5);
		gpio_set_value(p_tsdata->reset_pin, 1);
		msleep(300);
	}

	return 0;
}

static int edt_ft5x06_ts_identify(struct i2c_client *p_i2c_client,
					struct edt_ft5x06_ts_data *p_tsdata,
					char *fw_version)
{
	u8 rdbuf[EDT_NAME_LEN];
	char *p;
	int error;
	char *model_name = p_tsdata->name;

	/* see what we find if we assume it is a M06 *
	 * if we get less than EDT_NAME_LEN, we don't want
	 * to have garbage in there
	 */
	memset(rdbuf, 0, sizeof(rdbuf));
	error = edt_ft5x06_ts_readwrite(p_i2c_client, 1, "\xBB",
					EDT_NAME_LEN - 1, rdbuf);
	if (error)
		return error;

	/* probe content for something consistent.
	 * M06 starts with a response byte, M12 gives the data directly.
	 * M09/Generic does not provide model number information.
	 */
	if (!(strncasecmp(rdbuf + 1, "EP0", 3))) {
		p_tsdata->version = EDT_M06;

		/* remove last '$' end marker */
		rdbuf[EDT_NAME_LEN - 1] = '\0';
		if (rdbuf[EDT_NAME_LEN - 2] == '$')
			rdbuf[EDT_NAME_LEN - 2] = '\0';

		/* look for Model/Version separator */
		p = strchr(rdbuf, '*');
		if (p)
			*p++ = '\0';
		strlcpy(model_name, rdbuf + 1, EDT_NAME_LEN);
		strlcpy(fw_version, p ? p : "", EDT_NAME_LEN);
	} else if (!(strncasecmp(rdbuf, "EP0", 3))) {
		p_tsdata->version = EDT_M12;

		/* remove last '$' end marker */
		rdbuf[EDT_NAME_LEN - 2] = '\0';
		if (rdbuf[EDT_NAME_LEN - 3] == '$')
			rdbuf[EDT_NAME_LEN - 3] = '\0';

		/* look for Model/Version separator */
		p = strchr(rdbuf, '*');
		if (p)
			*p++ = '\0';
		strlcpy(model_name, rdbuf, EDT_NAME_LEN);
		strlcpy(fw_version, p ? p : "", EDT_NAME_LEN);
	} else {
		/* if it is not an EDT M06/M12 touchscreen then the model
		 * detection is a bit hairy. The different ft5x06
		 * firmares around don't reliably implement the
		 * identification registers. Well. we'll take a shot.
		 *
		 * the main difference between generic focaltec based
		 * touches and EDT M09 is, that we know how to retrieve
		 * the max coordinates for the latter */
		p_tsdata->version = GENERIC_FT;

		error = edt_ft5x06_ts_readwrite(p_i2c_client, 1, "\xA6",
						2, rdbuf);
		if (error)
			return error;

		strlcpy(fw_version, rdbuf, 2);

		error = edt_ft5x06_ts_readwrite(p_i2c_client, 1, "\xA8",
						1, rdbuf);
		if (error)
			return error;

		/* this "model identification is not exact. Unfortunately
                 * not all firmwares for the ft5x06 put useful values in
                 * the identification registers */
		switch (rdbuf[0]) {
		case 0x35:   /* EDT EP0350M09 */
		case 0x43:   /* EDT EP0430M09 */
		case 0x50:   /* EDT EP0500M09 */
		case 0x57:   /* EDT EP0570M09 */
		case 0x70:   /* EDT EP0700M09 */
			p_tsdata->version = EDT_M09;
			snprintf(model_name, EDT_NAME_LEN, "EP0%i%i0M09",
				rdbuf[0] >> 4, rdbuf[0] & 0x0F);
			break;
		case 0xa1:   /* EDT EP1010ML00 */
			p_tsdata->version = EDT_M09;
			snprintf(model_name, EDT_NAME_LEN, "EP%i%i0ML00",
				rdbuf[0] >> 4, rdbuf[0] & 0x0F);
			break;
		case 0x5a:   /* Solomon Goldentek Display */
			snprintf(model_name, EDT_NAME_LEN, "GKTW50SCED1R0");
			break;
		default:
			snprintf(model_name, EDT_NAME_LEN,
                                 "generic ft5x06 (%02x)",
				rdbuf[0]);
			break;
		}
	}

	return 0;
}

#define EDT_ATTR_CHECKSET(name, reg) \
do {								\
	if (pdata->name >= edt_ft5x06_attr_##name.limit_low &&		\
	    pdata->name <= edt_ft5x06_attr_##name.limit_high)		\
		edt_ft5x06_register_write(p_tsdata, reg, pdata->name);	\
} while (0)

#define EDT_GET_PROP(name, reg) {				\
	u32 val;						\
	if (of_property_read_u32(np, #name, &val) == 0)		\
		edt_ft5x06_register_write(p_tsdata, reg, val);	\
}

static void edt_ft5x06_ts_get_dt_defaults(struct device_node *np,
					struct edt_ft5x06_ts_data *p_tsdata)
{
	struct edt_reg_addr *reg_addr = &p_tsdata->reg_addr;

	EDT_GET_PROP(threshold, reg_addr->reg_threshold);
	EDT_GET_PROP(gain, reg_addr->reg_gain);
	EDT_GET_PROP(offset, reg_addr->reg_offset);
}

static void
edt_ft5x06_ts_get_defaults(struct edt_ft5x06_ts_data *p_tsdata,
			   const struct edt_ft5x06_platform_data *pdata)
{
	struct edt_reg_addr *reg_addr = &p_tsdata->reg_addr;

	if (!pdata->use_parameters)
		return;

	/* pick up defaults from the platform data */
	EDT_ATTR_CHECKSET(threshold, reg_addr->reg_threshold);
	EDT_ATTR_CHECKSET(gain, reg_addr->reg_gain);
	EDT_ATTR_CHECKSET(offset, reg_addr->reg_offset);
	if (reg_addr->reg_report_rate != NO_REGISTER)
		EDT_ATTR_CHECKSET(report_rate, reg_addr->reg_report_rate);
}

static void
edt_ft5x06_ts_get_parameters(struct edt_ft5x06_ts_data *p_tsdata)
{
	int reg_value;
	struct edt_reg_addr *p_reg_addr = &p_tsdata->reg_addr;

	p_tsdata->threshold = edt_ft5x06_register_read(p_tsdata,
						p_reg_addr->reg_threshold);
	p_tsdata->gain = edt_ft5x06_register_read(p_tsdata,
						  p_reg_addr->reg_gain);
	p_tsdata->offset = edt_ft5x06_register_read(p_tsdata,
						    p_reg_addr->reg_offset);
	if (p_reg_addr->reg_report_rate != NO_REGISTER)
		p_tsdata->report_rate = edt_ft5x06_register_read(p_tsdata,
						p_reg_addr->reg_report_rate);

	p_tsdata->dimension.x = EDT_INVALID_POINT;
	p_tsdata->dimension.y = EDT_INVALID_POINT;

	if (p_tsdata->version == EDT_M06 ||
	    p_tsdata->version == EDT_M09 ||
	    p_tsdata->version == EDT_M12) {

		reg_value = edt_ft5x06_register_read(p_tsdata,
						 p_reg_addr->reg_num_x);
		if( reg_value > 0 )
			p_tsdata->dimension.x =
				EDT_DIMENSION_TO_COORDINATE(reg_value);

		reg_value = edt_ft5x06_register_read(p_tsdata,
						 p_reg_addr->reg_num_y);
		if( reg_value > 0 )
			p_tsdata->dimension.y =
				EDT_DIMENSION_TO_COORDINATE(reg_value);
	}
}

static void
edt_ft5x06_ts_set_regs(struct edt_ft5x06_ts_data *p_tsdata)
{
	struct edt_reg_addr *p_reg_addr = &p_tsdata->reg_addr;

	switch (p_tsdata->version) {
	case EDT_M06:
		p_reg_addr->reg_threshold = WORK_REGISTER_THRESHOLD;
		p_reg_addr->reg_report_rate = WORK_REGISTER_REPORT_RATE;
		p_reg_addr->reg_gain = WORK_REGISTER_GAIN;
		p_reg_addr->reg_offset = WORK_REGISTER_OFFSET;
		p_reg_addr->reg_num_x = WORK_REGISTER_NUM_X;
		p_reg_addr->reg_num_y = WORK_REGISTER_NUM_Y;
		break;

	case EDT_M09:
	case EDT_M12:
		p_reg_addr->reg_threshold = M09_REGISTER_THRESHOLD;
		p_reg_addr->reg_gain = M09_REGISTER_GAIN;
		p_reg_addr->reg_offset = M09_REGISTER_OFFSET;
		p_reg_addr->reg_num_x = M09_REGISTER_NUM_X;
		p_reg_addr->reg_num_y = M09_REGISTER_NUM_Y;
		break;

	case GENERIC_FT:
		/* this is guesswork */
		p_reg_addr->reg_threshold = M09_REGISTER_THRESHOLD;
		p_reg_addr->reg_gain = M09_REGISTER_GAIN;
		p_reg_addr->reg_offset = M09_REGISTER_OFFSET;
		break;
	}
}

#ifdef CONFIG_OF
static int edt_ft5x06_i2c_ts_probe_dt(struct device *dev,
				struct edt_ft5x06_ts_data *p_tsdata)
{
	struct device_node *np = dev->of_node;

	/*
	 * irq_pin is not needed for DT setup.
	 * irq is associated via 'interrupts' property in DT
	 */
	p_tsdata->irq_pin = -EINVAL;
	p_tsdata->reset_pin = of_get_named_gpio(np, "reset-gpios", 0);
	p_tsdata->wake_pin = of_get_named_gpio(np, "wake-gpios", 0);

	return 0;
}
#else
static inline int edt_ft5x06_i2c_ts_probe_dt(struct device *dev,
					struct edt_ft5x06_ts_data *p_tsdata)
{
	return -ENODEV;
}
#endif

static int edt_ft5x06_ts_probe(struct i2c_client *p_i2c_client,
				 const struct i2c_device_id *p_i2c_id)
{
	const struct edt_ft5x06_platform_data *p_platform_data =
					dev_get_platdata(&p_i2c_client->dev);
	struct edt_ft5x06_ts_data* p_tsdata;
	struct input_dev* p_input_dev;
	int error, i;
	char fw_version[EDT_NAME_LEN];

	dev_dbg(&p_i2c_client->dev, "probing for EDT FT5x06 I2C\n");

	p_tsdata = devm_kzalloc(&p_i2c_client->dev,
				sizeof(*p_tsdata), GFP_KERNEL);
	if (!p_tsdata) {
		dev_err(&p_i2c_client->dev,
			"failed to allocate driver data.\n");
		return -ENOMEM;
	}

	if (!p_platform_data) {
		error = edt_ft5x06_i2c_ts_probe_dt(&p_i2c_client->dev,
						   p_tsdata);
		if (error) {
			dev_err(&p_i2c_client->dev,
				"DT probe failed and no platform data"
				" present\n");
			return error;
		}
	} else {
		p_tsdata->reset_pin = p_platform_data->reset_pin;
		p_tsdata->irq_pin = p_platform_data->irq_pin;
		p_tsdata->wake_pin = -EINVAL;
	}

	error = edt_ft5x06_ts_reset(p_i2c_client, p_tsdata);
	if (error)
		return error;

	if (gpio_is_valid(p_tsdata->irq_pin)) {
		error = devm_gpio_request_one(&p_i2c_client->dev,
						p_tsdata->irq_pin,
						GPIOF_IN, "edt-ft5x06 irq");
		if (error) {
			dev_err(&p_i2c_client->dev,
				"Failed to request GPIO %d, error %d\n",
				p_tsdata->irq_pin, error);
			return error;
		}
	}

	p_input_dev = devm_input_allocate_device(&p_i2c_client->dev);
	if (!p_input_dev) {
		dev_err(&p_i2c_client->dev, 
			"failed to allocate input device.\n");
		return -ENOMEM;
	}

	spin_lock_init(&p_tsdata->spinlock);
	p_tsdata->p_i2c_client = p_i2c_client;
	p_tsdata->p_input_dev = p_input_dev;
	p_tsdata->factory_mode = false;

	error = edt_ft5x06_ts_identify(p_i2c_client, p_tsdata, fw_version);
	if (error) {
		dev_err(&p_i2c_client->dev, "touchscreen probe failed\n");
		return error;
	}

	edt_ft5x06_ts_set_regs(p_tsdata);

	if (!p_platform_data)
		edt_ft5x06_ts_get_dt_defaults(p_i2c_client->dev.of_node,
					      p_tsdata);
	else
		edt_ft5x06_ts_get_defaults(p_tsdata, p_platform_data);

	edt_ft5x06_ts_get_parameters(p_tsdata);

	dev_dbg(&p_i2c_client->dev,
		"Model \"%s\", Rev. \"%s\", %dx%d sensors\n",
		p_tsdata->name, fw_version, p_tsdata->dimension.x,
		p_tsdata->dimension.y);

	setup_timer(&p_tsdata->touch_up_timer, edt_ft5x06_touch_up_timer,
		    (unsigned long) p_tsdata);
	p_tsdata->min_receive_count = EDT_DEFAULT_MIN_RECEIVE_COUNT;
	p_tsdata->touch_timeout = EDT_DEFAULT_TUOCH_TIMEOUT;
#ifdef CONFIG_EDT_BORDERS
	p_tsdata->border_up = EDT_DEFAULT_BORDER;
	p_tsdata->border_down = EDT_DEFAULT_BORDER;
	p_tsdata->border_left = EDT_DEFAULT_BORDER;
	p_tsdata->border_right = EDT_DEFAULT_BORDER;
#endif
#ifdef CONFIG_EDT_IRQ_TOO_EARLY_CHECK
	p_tsdata->irq_timestamp = jiffies;
	p_tsdata->min_irq_interval_time = IRQ_DEFAULT_MIN_INTERVAL_TIME;
#endif
	p_tsdata->touch_maxdistance = 0;
	for (i = 0; i < MAX_SUPPORT_POINTS; i++) {
		p_tsdata->a_contacts[i].time_stamp = 0;
		p_tsdata->a_contacts[i].touch_on_receive_count = 0;
		p_tsdata->a_contacts[i].was_new_input_read = false;
#ifdef CONFIG_EDT_TOUCH_DOWN_CHECK
		p_tsdata->a_contacts[i].is_down = false;
#endif
		p_tsdata->a_contacts[i].id = i;
		p_tsdata->a_contacts[i].ev_type = TOUCH_EVENT_NON;
		p_tsdata->a_contacts[i].point.x = EDT_INVALID_POINT;
		p_tsdata->a_contacts[i].point.y = EDT_INVALID_POINT;
	}

	p_input_dev->name = p_tsdata->name;
	p_input_dev->id.bustype = BUS_I2C;
	p_input_dev->dev.parent = &p_i2c_client->dev;

	__set_bit(EV_KEY, p_input_dev->evbit);
	__set_bit(EV_ABS, p_input_dev->evbit);
	__set_bit(BTN_TOUCH, p_input_dev->keybit);

	if (p_tsdata->version == EDT_M06 ||
	    p_tsdata->version == EDT_M09 ||
	    p_tsdata->version == EDT_M12) {
		input_set_abs_params(p_input_dev, ABS_X, 0, 
				p_tsdata->dimension.x, 0, 0);
		input_set_abs_params(p_input_dev, ABS_Y, 0,
				p_tsdata->dimension.y, 0, 0);
		input_set_abs_params(p_input_dev, ABS_MT_POSITION_X,
				0, p_tsdata->dimension.x, 0, 0);
		input_set_abs_params(p_input_dev, ABS_MT_POSITION_Y,
				0, p_tsdata->dimension.y, 0, 0);
	} else {
		/* unknown maximum values. Specify via devicetree */
		input_set_abs_params(p_input_dev, ABS_X, 0, 65535, 0, 0);
		input_set_abs_params(p_input_dev, ABS_Y, 0, 65535, 0, 0);
		input_set_abs_params(p_input_dev, ABS_MT_POSITION_X,
				     0, 65535, 0, 0);
		input_set_abs_params(p_input_dev, ABS_MT_POSITION_Y,
				     0, 65535, 0, 0);
	}

	if (!p_platform_data)
		touchscreen_parse_of_params(p_input_dev);

	error = input_mt_init_slots(p_input_dev, MAX_SUPPORT_POINTS, 0);
	if (error) {
		dev_err(&p_i2c_client->dev, "Unable to init MT slots.\n");
		return error;
	}

	input_set_drvdata(p_input_dev, p_tsdata);
	i2c_set_clientdata(p_i2c_client, p_tsdata);

	error = devm_request_threaded_irq(&p_i2c_client->dev, 
					p_i2c_client->irq, NULL,
					edt_ft5x06_ts_isr,
					IRQF_TRIGGER_FALLING | IRQF_ONESHOT,
					p_i2c_client->name, p_tsdata);
	if (error) {
		dev_err(&p_i2c_client->dev,
			"Unable to request touchscreen IRQ.\n");
		return error;
	}

	error = sysfs_create_group(&p_i2c_client->dev.kobj,
				   &edt_ft5x06_attr_group);
	if (error)
		return error;

	error = input_register_device(p_input_dev);
	if (error)
		goto err_remove_attrs;

	edt_ft5x06_ts_prepare_debugfs(p_tsdata,
				      dev_driver_string(&p_i2c_client->dev));
	device_init_wakeup(&p_i2c_client->dev, 1);

	dev_dbg(&p_i2c_client->dev,
		"EDT FT5x06 initialized: IRQ %d, WAKE pin %d, Reset pin %d.\n",
		p_i2c_client->irq, p_tsdata->wake_pin, p_tsdata->reset_pin);

	return 0;

err_remove_attrs:
	sysfs_remove_group(&p_i2c_client->dev.kobj, &edt_ft5x06_attr_group);
	return error;
}

static int edt_ft5x06_ts_remove(struct i2c_client *client)
{
	struct edt_ft5x06_ts_data *p_tsdata = i2c_get_clientdata(client);

	edt_ft5x06_ts_teardown_debugfs(p_tsdata);
	sysfs_remove_group(&client->dev.kobj, &edt_ft5x06_attr_group);
	free_irq(client->irq, p_tsdata);
	del_timer_sync(&p_tsdata->touch_up_timer);
	input_unregister_device(p_tsdata->p_input_dev);
	return 0;
}

static int __maybe_unused edt_ft5x06_ts_suspend(struct device *dev)
{
	struct i2c_client *client = to_i2c_client(dev);

	if (device_may_wakeup(dev))
		enable_irq_wake(client->irq);

	return 0;
}

static int __maybe_unused edt_ft5x06_ts_resume(struct device *dev)
{
	struct i2c_client *client = to_i2c_client(dev);

	if (device_may_wakeup(dev))
		disable_irq_wake(client->irq);

	return 0;
}

static SIMPLE_DEV_PM_OPS(edt_ft5x06_ts_pm_ops,
			 edt_ft5x06_ts_suspend, edt_ft5x06_ts_resume);

static const struct i2c_device_id edt_ft5x06_ts_id[] = {
	{ "edt-ft5x06", 0, },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(i2c, edt_ft5x06_ts_id);

#ifdef CONFIG_OF
static const struct of_device_id edt_ft5x06_of_match[] = {
	{ .compatible = "edt,edt-ft5206", },
	{ .compatible = "edt,edt-ft5306", },
	{ .compatible = "edt,edt-ft5406", },
	{ /* sentinel */ }
};
MODULE_DEVICE_TABLE(of, edt_ft5x06_of_match);
#endif

static struct i2c_driver edt_ft5x06_ts_driver = {
	.driver = {
		.owner = THIS_MODULE,
		.name = "edt_ft5x06",
		.of_match_table = of_match_ptr(edt_ft5x06_of_match),
		.pm = &edt_ft5x06_ts_pm_ops,
	},
	.id_table = edt_ft5x06_ts_id,
	.probe    = edt_ft5x06_ts_probe,
	.remove   = edt_ft5x06_ts_remove,
};

module_i2c_driver(edt_ft5x06_ts_driver);

MODULE_AUTHOR("Simon Budig <simon.budig@kernelconcepts.de>");
MODULE_DESCRIPTION("EDT FT5x06 I2C Touchscreen Driver");
MODULE_LICENSE("GPL");
/*================================== EOF ====================================*/

